#!/usr/bin/env bash
# Install the JustSoc probe stack on this host.
#
# Layout this script expects (produced by ./build.sh + ./init-config.sh):
#   bin/selk-probe-linux-amd64
#   bin/threat-engine
#   monitor/selk-runtime-monitor.py
#   monitor/selk-runtime-control.sh
#   configs/probe-stack.env            (single human-edited config)
#   configs/probe.example.yaml         (template, shipped)
#   configs/engine-rules.yaml          (rule data, shipped)
#   configs/probe.yaml                 (generated by init-config.sh)
#   configs/suricata.generated.yaml    (generated by init-config.sh)
#   configs/probe-whitelist.generated.bpf (generated by init-config.sh)
#   suricata-rules/*.rules
#
# Generates:
#   configs/engine.conf
#   configs/runtime-monitor.env
#   configs/dispatcher.shared_secret   (hmac mode only)
#
# Writes systemd units to /etc/systemd/system/ and starts them.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_ROOT="$SCRIPT_DIR"
STACK_ENV="${SELK_PROBE_STACK_ENV:-$INSTALL_ROOT/configs/probe-stack.env}"

if [[ ! -f "$STACK_ENV" ]]; then
  echo "missing $STACK_ENV; run ./init-config.sh first to create it." >&2
  exit 1
fi

# Strip Windows CRLF line endings if the env file was edited on Windows.
if LC_ALL=C grep -q $'\r' "$STACK_ENV"; then
  sed -i 's/\r$//' "$STACK_ENV"
  echo "normalized CRLF -> LF: $STACK_ENV"
fi

set -a
# shellcheck disable=SC1090
source "$STACK_ENV"
set +a

SYSTEMD_DIR="${SYSTEMD_DIR:-${SELK_SYSTEMD_DIR:-/etc/systemd/system}}"
PROBE_SERVICE_NAME="${SELK_PROBE_SERVICE:-selk-probe}"
ENGINE_SERVICE_NAME="${SELK_ENGINE_SERVICE:-justsoc-threat-engine}"
DISPATCHER_SERVICE_NAME="${SELK_DISPATCHER_SERVICE:-selk-probe-dispatcher}"
LOG_DIR="${SELK_LOG_DIR:-/var/log/selk}"
RUN_DIR="${SELK_RUN_DIR:-/run/selk}"

PROBE_BIN="$INSTALL_ROOT/bin/selk-probe-linux-amd64"
ENGINE_BIN="$INSTALL_ROOT/bin/threat-engine"
MONITOR_SCRIPT="$INSTALL_ROOT/monitor/selk-runtime-monitor.py"
CONTROL_SCRIPT="$INSTALL_ROOT/monitor/selk-runtime-control.sh"
PROBE_CONFIG="$INSTALL_ROOT/configs/probe.yaml"
SURICATA_CONFIG="$INSTALL_ROOT/configs/suricata.generated.yaml"
ENGINE_RULES="$INSTALL_ROOT/configs/engine-rules.yaml"
ENGINE_CONF="$INSTALL_ROOT/configs/engine.conf"
RUNTIME_ENV="$INSTALL_ROOT/configs/runtime-monitor.env"

require_file() {
  local path="$1" hint="$2"
  if [[ ! -f "$path" ]]; then
    echo "missing required file: $path ($hint)" >&2
    exit 1
  fi
}

require_python_yaml() {
  python3 - <<'PY'
import yaml  # noqa: F401
PY
}

resolve_install_path() {
  local value="$1"
  local fallback="$2"
  if [[ -z "$value" ]]; then
    value="$fallback"
  fi
  if [[ -z "$value" ]]; then
    printf '\n'
    return
  fi
  if [[ "$value" = /* ]]; then
    printf '%s\n' "$value"
  else
    printf '%s/%s\n' "$INSTALL_ROOT" "$value"
  fi
}

install_dispatcher_secret() {
  local auth_mode="${SELK_DISPATCH_AUTH_MODE:-hmac}"
  if [[ "$auth_mode" != "hmac" ]]; then
    return
  fi

  local target
  target="$(resolve_install_path "${SELK_DISPATCH_SHARED_SECRET_FILE:-}" "configs/dispatcher.shared_secret")"
  if [[ -f "$target" ]]; then
    echo "keep existing $target (run ./generate-secret.sh --show to print, --force to rotate)"
    return
  fi

  # Delegate to generate-secret.sh so the secret is printed to the console
  # exactly once -- right when it is created.
  "$INSTALL_ROOT/generate-secret.sh"
}

generate_runtime_monitor_env() {
  local target="$RUNTIME_ENV"
  local secret_file bearer_file asset_root health_listen health_port
  secret_file="$(resolve_install_path "${SELK_DISPATCH_SHARED_SECRET_FILE:-}" "configs/dispatcher.shared_secret")"
  bearer_file="$(resolve_install_path "${SELK_DISPATCH_BEARER_TOKEN_FILE:-}" "")"
  asset_root="$(resolve_install_path "${SELK_ASSET_CONFIG_ROOT:-}" "assets")"
  health_listen="${SELK_PROBE_HEALTH_LISTEN:-:8081}"
  health_port="${health_listen##*:}"
  if [[ -z "$health_port" ]]; then
    health_port="8081"
  fi

  mkdir -p "$(dirname "$target")"
  cat > "$target" <<EOF
# Generated from configs/probe-stack.env by install.sh. Do not edit by hand.
SELK_RUNTIME_BIND=${SELK_RUNTIME_BIND:-0.0.0.0}
SELK_RUNTIME_PORT=${SELK_RUNTIME_PORT:-19091}
SELK_RUNTIME_METRICS_PATH=${SELK_RUNTIME_METRICS_PATH:-/_selk_internal/v1/runtime-pulse/9f3a7c4e61/metrics}
SELK_RUNTIME_CONTROL_PATH=${SELK_RUNTIME_CONTROL_PATH:-/_selk_internal/v1/control-plane/9f3a7c4e61/restart}
SELK_RUNTIME_STATUS_PATH=${SELK_RUNTIME_STATUS_PATH:-$RUN_DIR/runtime-status.json}
SELK_RUNTIME_POLL_SECONDS=${SELK_RUNTIME_POLL_SECONDS:-60}
SELK_RUNTIME_STALE_SECONDS=${SELK_RUNTIME_STALE_SECONDS:-300}
SELK_PROBE_PROD_ROOT=$INSTALL_ROOT
SELK_PROBE_SERVICE=${PROBE_SERVICE_NAME}.service
SELK_ENGINE_SERVICE=${ENGINE_SERVICE_NAME}.service
SELK_PROBE_HEALTH_URL=${SELK_PROBE_HEALTH_URL:-http://127.0.0.1:${health_port}/healthz}
SELK_PROBE_READY_URL=${SELK_PROBE_READY_URL:-http://127.0.0.1:${health_port}/readyz}
SELK_PROBE_LOG_PATH=${SELK_PROBE_LOG_PATH:-$LOG_DIR/selk-probe.log}
SELK_ENGINE_LOG_PATH=${SELK_ENGINE_LOG_PATH:-$LOG_DIR/threat-engine.log}
SELK_SURICATA_EVE_PATH=${SELK_SURICATA_EVE_PATH:-/var/log/suricata/eve.json}
SELK_SURICATA_PROCESS=${SELK_SURICATA_PROCESS:-suricata}
SELK_DISPATCH_AUTH_MODE=${SELK_DISPATCH_AUTH_MODE:-hmac}
SELK_DISPATCH_KEY_ID=${SELK_DISPATCH_KEY_ID:-probe-prod-dispatcher}
SELK_DISPATCH_SHARED_SECRET_FILE=$secret_file
SELK_DISPATCH_BEARER_TOKEN=${SELK_DISPATCH_BEARER_TOKEN:-}
SELK_DISPATCH_BEARER_TOKEN_FILE=$bearer_file
SELK_ASSET_APPLY_PATH=${SELK_ASSET_APPLY_PATH:-/_selk_internal/v1/assets/apply}
SELK_ASSET_STATUS_PATH=${SELK_ASSET_STATUS_PATH:-/_selk_internal/v1/assets/status}
SELK_ASSET_VALIDATE_PATH=${SELK_ASSET_VALIDATE_PATH:-/_selk_internal/v1/assets/validate}
SELK_ASSET_ROLLBACK_PATH=${SELK_ASSET_ROLLBACK_PATH:-/_selk_internal/v1/assets/rollback}
SELK_ASSET_CONFIG_ROOT=$asset_root
EOF
  echo "generated $target"
}

generate_engine_conf() {
  local target="$ENGINE_CONF"
  mkdir -p "$(dirname "$target")"
  python3 - "$target" <<'PY'
import json
import os
import sys

target = sys.argv[1]

def env(key, default=""):
    return os.environ.get(key, default).strip()

def env_int(key, default):
    value = env(key)
    if not value:
        return default
    return int(value)

def env_bool(key, default=False):
    value = env(key)
    if not value:
        return default
    return value.lower() in {"1", "true", "yes", "on"}

def csv(key, default):
    raw = env(key, default)
    return [item.strip() for item in raw.split(",") if item.strip()]

# Paths below are relative to the directory containing engine.conf
# (deploy/configs/), resolved by threat-engine's runtimeconfig loader.
config = {
    "debug": env_bool("SELK_ENGINE_DEBUG", False),
    "kafka": {
        "bootstrap_servers": csv("SELK_KAFKA_BOOTSTRAP_SERVERS", "127.0.0.1:9092"),
        "security_protocol": env("SELK_KAFKA_SECURITY_PROTOCOL", ""),
        "sasl": {
            "mechanism": env("SELK_KAFKA_SASL_MECHANISM", "PLAIN"),
            "username": env("SELK_KAFKA_USERNAME", ""),
            "password": env("SELK_KAFKA_PASSWORD", ""),
        },
    },
    "consumer": {
        "topic": env("SELK_KAFKA_RAW_TOPIC", "selk.suricata.eve"),
        "group_id": env("SELK_ENGINE_CONSUMER_GROUP", "justsoc-threat-engine"),
    },
    "sink": {
        "mode": env("SELK_ENGINE_SINK_MODE", "kafka"),
        "batch_size": env_int("SELK_ENGINE_BATCH_SIZE", 100),
        "flush_interval_ms": env_int("SELK_ENGINE_FLUSH_INTERVAL_MS", 50),
        "queue_size": env_int("SELK_ENGINE_QUEUE_SIZE", 1000),
        "workers": 1,
        "kafka": {
            "topic": env("SELK_KAFKA_ENRICHED_TOPIC", "selk.alerts.enriched"),
        },
        "es": {
            "endpoint": env("SELK_ENGINE_ES_ENDPOINT", "http://127.0.0.1:9200"),
            "index": env("SELK_ENGINE_ES_INDEX", "selk-suricata-%{+YYYY.MM.dd}"),
        },
    },
    "whitelist": {
        "path": env("SELK_ENGINE_WHITELIST_PATH", ""),
    },
    "rules": {
        "path": env("SELK_ENGINE_RULES_PATH", "engine-rules.yaml"),
        "suricata_dir": env("SELK_ENGINE_SURICATA_RULE_DIR", "../suricata-rules"),
    },
    "assets": {
        "path": env("SELK_ENGINE_ASSET_CONFIG_PATH", "../assets/current/assets.yaml"),
    },
}

with open(target, "w", encoding="utf-8") as handle:
    json.dump(config, handle, indent=2, ensure_ascii=False)
    handle.write("\n")
PY
  echo "generated $target"
}

write_probe_service() {
  cat > "$SYSTEMD_DIR/${PROBE_SERVICE_NAME}.service" <<EOF
[Unit]
Description=JustSoc Probe
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${INSTALL_ROOT}
EnvironmentFile=-${STACK_ENV}
ExecStartPre=/usr/bin/mkdir -p ${LOG_DIR}
ExecStart=${PROBE_BIN} -config ${PROBE_CONFIG}
Restart=always
RestartSec=5
LimitNOFILE=65535
StandardOutput=append:${LOG_DIR}/selk-probe.log
StandardError=append:${LOG_DIR}/selk-probe.log

[Install]
WantedBy=multi-user.target
EOF
}

write_engine_service() {
  cat > "$SYSTEMD_DIR/${ENGINE_SERVICE_NAME}.service" <<EOF
[Unit]
Description=JustSoc Threat Engine
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${INSTALL_ROOT}
EnvironmentFile=-${STACK_ENV}
ExecStartPre=/usr/bin/mkdir -p ${LOG_DIR}
ExecStart=${ENGINE_BIN} -config ${ENGINE_CONF}
Restart=always
RestartSec=5
StandardOutput=append:${LOG_DIR}/threat-engine.log
StandardError=append:${LOG_DIR}/threat-engine.log

[Install]
WantedBy=multi-user.target
EOF
}

write_dispatcher_service() {
  cat > "$SYSTEMD_DIR/${DISPATCHER_SERVICE_NAME}.service" <<EOF
[Unit]
Description=JustSoc Probe Dispatcher
After=network-online.target ${PROBE_SERVICE_NAME}.service ${ENGINE_SERVICE_NAME}.service
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${INSTALL_ROOT}
EnvironmentFile=-${STACK_ENV}
EnvironmentFile=-${RUNTIME_ENV}
ExecStartPre=/usr/bin/mkdir -p ${RUN_DIR}
ExecStart=/usr/bin/python3 ${MONITOR_SCRIPT}
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
}

require_file "$PROBE_BIN"                     "run ./build.sh"
require_file "$ENGINE_BIN"                    "run ./build.sh"
require_file "$MONITOR_SCRIPT"                "run ./build.sh"
require_file "$CONTROL_SCRIPT"                "run ./build.sh"
require_file "$ENGINE_RULES"                  "run ./build.sh"
require_file "$INSTALL_ROOT/generate-secret.sh" "ship generate-secret.sh alongside install.sh"
require_file "$PROBE_CONFIG"                  "run ./init-config.sh"
require_file "$SURICATA_CONFIG"               "run ./init-config.sh"
require_python_yaml

mkdir -p "$SYSTEMD_DIR" "$LOG_DIR" "$RUN_DIR"
chmod 0755 "$PROBE_BIN" "$ENGINE_BIN" "$MONITOR_SCRIPT" "$CONTROL_SCRIPT"

install_dispatcher_secret
generate_runtime_monitor_env
generate_engine_conf

write_probe_service
write_engine_service
write_dispatcher_service

systemctl daemon-reload
systemctl enable --now "${PROBE_SERVICE_NAME}.service"
systemctl enable --now "${ENGINE_SERVICE_NAME}.service"
systemctl enable --now "${DISPATCHER_SERVICE_NAME}.service"

cat <<EOF

installed root:      $INSTALL_ROOT
editable config:     $STACK_ENV
generated configs:   $RUNTIME_ENV
                     $ENGINE_CONF
services:            ${PROBE_SERVICE_NAME}, ${ENGINE_SERVICE_NAME}, ${DISPATCHER_SERVICE_NAME}
dispatcher url:      http://${SELK_RUNTIME_BIND:-0.0.0.0}:${SELK_RUNTIME_PORT:-19091}
control helper:      ${CONTROL_SCRIPT} restart probe
EOF
