export type AlertFieldPathMode = 'same' | 'keyword';

export type AlertFieldMappingKey =
  | 'timestamp'
  | 'eventType'
  | 'alertSignature'
  | 'eventSeverity'
  | 'srcIp'
  | 'srcPort'
  | 'destIp'
  | 'destPort'
  | 'proto'
  | 'appProto'
  | 'sensorId'
  | 'probeHost'
  | 'httpMethod'
  | 'httpHostname'
  | 'httpUrl'
  | 'httpStatus'
  | 'httpLength'
  | 'attackCategory'
  | 'attackStage'
  | 'attackSuccess'
  | 'attackSuccessConfidence'
  | 'attackSuccessReason'
  | 'payloadPrintable'
  | 'payload'
  | 'packet';

export type AlertFieldMappings = Record<AlertFieldMappingKey, string>;

export type AlertFieldMappingSchemaItem = {
  key: AlertFieldMappingKey;
  label: string;
  description: string;
  placeholder: string;
  defaultValue: string;
  legacyAliases?: string[];
  type: string;
  searchable: boolean;
  aggregatable: boolean;
  defaultSelected: boolean;
  detailOnly: boolean;
  statsKind: 'terms' | 'date_histogram' | 'none';
  aggregationFieldMode: AlertFieldPathMode;
  sortFieldMode: AlertFieldPathMode;
  queryFieldMode: AlertFieldPathMode;
};

export const ALERT_TITLE_FIELD_KEY: AlertFieldMappingKey = 'alertSignature';

export const alertFieldMappingSchema: AlertFieldMappingSchemaItem[] = [
  {
    key: 'timestamp',
    label: '时间',
    description: '告警时间，用于排序、时间过滤和时间分布统计。',
    placeholder: '@timestamp',
    defaultValue: '@timestamp',
    type: 'date',
    searchable: true,
    aggregatable: true,
    defaultSelected: true,
    detailOnly: false,
    statsKind: 'date_histogram',
    aggregationFieldMode: 'same',
    sortFieldMode: 'same',
    queryFieldMode: 'same',
  },
  {
    key: 'eventType',
    label: '日志类型',
    description: '日志或事件类型字段。',
    placeholder: 'event_type',
    defaultValue: 'event_type',
    type: 'keyword',
    searchable: true,
    aggregatable: true,
    defaultSelected: false,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'keyword',
    sortFieldMode: 'keyword',
    queryFieldMode: 'keyword',
  },
  {
    key: 'alertSignature',
    label: '告警标题',
    description: '规则标题或告警名称，默认用于主标题列。',
    placeholder: 'alert.signature',
    defaultValue: 'alert.signature',
    type: 'keyword',
    searchable: true,
    aggregatable: true,
    defaultSelected: true,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'keyword',
    sortFieldMode: 'keyword',
    queryFieldMode: 'same',
  },
  {
    key: 'eventSeverity',
    label: '严重级别',
    description: '告警严重级别字段。',
    placeholder: 'event.severity',
    defaultValue: 'event.severity',
    legacyAliases: ['alert.severity'],
    type: 'keyword',
    searchable: true,
    aggregatable: true,
    defaultSelected: true,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'keyword',
    sortFieldMode: 'keyword',
    queryFieldMode: 'keyword',
  },
  {
    key: 'srcIp',
    label: '源 IP',
    description: '攻击来源 IP。',
    placeholder: 'src_ip',
    defaultValue: 'src_ip',
    type: 'keyword',
    searchable: true,
    aggregatable: true,
    defaultSelected: true,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'keyword',
    sortFieldMode: 'keyword',
    queryFieldMode: 'keyword',
  },
  {
    key: 'srcPort',
    label: '源端口',
    description: '来源端口。',
    placeholder: 'src_port',
    defaultValue: 'src_port',
    type: 'integer',
    searchable: true,
    aggregatable: true,
    defaultSelected: true,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'same',
    sortFieldMode: 'same',
    queryFieldMode: 'same',
  },
  {
    key: 'destIp',
    label: '目标 IP',
    description: '目标 IP。',
    placeholder: 'dest_ip',
    defaultValue: 'dest_ip',
    type: 'keyword',
    searchable: true,
    aggregatable: true,
    defaultSelected: true,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'keyword',
    sortFieldMode: 'keyword',
    queryFieldMode: 'keyword',
  },
  {
    key: 'destPort',
    label: '目标端口',
    description: '目标端口。',
    placeholder: 'dest_port',
    defaultValue: 'dest_port',
    type: 'integer',
    searchable: true,
    aggregatable: true,
    defaultSelected: true,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'same',
    sortFieldMode: 'same',
    queryFieldMode: 'same',
  },
  {
    key: 'proto',
    label: '传输协议',
    description: '网络传输层协议。',
    placeholder: 'proto',
    defaultValue: 'proto',
    type: 'keyword',
    searchable: true,
    aggregatable: true,
    defaultSelected: true,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'keyword',
    sortFieldMode: 'keyword',
    queryFieldMode: 'keyword',
  },
  {
    key: 'appProto',
    label: '应用协议',
    description: '应用层协议类型。',
    placeholder: 'app_proto',
    defaultValue: 'app_proto',
    type: 'keyword',
    searchable: true,
    aggregatable: true,
    defaultSelected: true,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'keyword',
    sortFieldMode: 'keyword',
    queryFieldMode: 'keyword',
  },
  {
    key: 'sensorId',
    label: '传感器',
    description: '采集或检测节点标识。',
    placeholder: 'sensor_id',
    defaultValue: 'sensor_id',
    type: 'keyword',
    searchable: true,
    aggregatable: true,
    defaultSelected: true,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'keyword',
    sortFieldMode: 'keyword',
    queryFieldMode: 'keyword',
  },
  {
    key: 'probeHost',
    label: '探针主机',
    description: '探针主机名字段。',
    placeholder: 'probe.host',
    defaultValue: 'probe.host',
    type: 'keyword',
    searchable: true,
    aggregatable: true,
    defaultSelected: true,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'keyword',
    sortFieldMode: 'keyword',
    queryFieldMode: 'keyword',
  },
  {
    key: 'httpMethod',
    label: 'HTTP 方法',
    description: 'HTTP 请求方法。',
    placeholder: 'correlated_http.http.http_method',
    defaultValue: 'correlated_http.http.http_method',
    type: 'keyword',
    searchable: true,
    aggregatable: true,
    defaultSelected: true,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'keyword',
    sortFieldMode: 'keyword',
    queryFieldMode: 'keyword',
  },
  {
    key: 'httpHostname',
    label: 'HTTP 主机',
    description: 'HTTP Host 或主机名。',
    placeholder: 'correlated_http.http.hostname',
    defaultValue: 'correlated_http.http.hostname',
    type: 'keyword',
    searchable: true,
    aggregatable: true,
    defaultSelected: true,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'keyword',
    sortFieldMode: 'keyword',
    queryFieldMode: 'keyword',
  },
  {
    key: 'httpUrl',
    label: 'HTTP URL',
    description: 'HTTP 请求 URL。',
    placeholder: 'http.url',
    defaultValue: 'http.url',
    legacyAliases: ['correlated_http.http.url'],
    type: 'keyword',
    searchable: true,
    aggregatable: true,
    defaultSelected: true,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'keyword',
    sortFieldMode: 'keyword',
    queryFieldMode: 'same',
  },
  {
    key: 'httpStatus',
    label: 'HTTP 状态码',
    description: 'HTTP 响应状态码。',
    placeholder: 'http.status',
    defaultValue: 'http.status',
    legacyAliases: ['correlated_http.http.status'],
    type: 'integer',
    searchable: true,
    aggregatable: true,
    defaultSelected: false,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'same',
    sortFieldMode: 'same',
    queryFieldMode: 'same',
  },
  {
    key: 'httpLength',
    label: 'HTTP Content-Length',
    description: 'HTTP 响应包 Content-Length。',
    placeholder: 'http.length',
    defaultValue: 'http.length',
    type: 'integer',
    searchable: true,
    aggregatable: true,
    defaultSelected: false,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'same',
    sortFieldMode: 'same',
    queryFieldMode: 'same',
  },
  {
    key: 'attackCategory',
    label: '攻击类型',
    description: 'JustSoc 归一化后的攻击类型。',
    placeholder: 'alert.metadata.selk_category',
    defaultValue: 'alert.metadata.selk_category',
    type: 'keyword',
    searchable: true,
    aggregatable: true,
    defaultSelected: false,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'same',
    sortFieldMode: 'same',
    queryFieldMode: 'same',
  },
  {
    key: 'attackStage',
    label: '攻击阶段',
    description: '攻击阶段判断结果。',
    placeholder: 'engine.attack_stage',
    defaultValue: 'engine.attack_stage',
    type: 'keyword',
    searchable: true,
    aggregatable: true,
    defaultSelected: false,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'same',
    sortFieldMode: 'same',
    queryFieldMode: 'same',
  },
  {
    key: 'attackSuccess',
    label: '攻击成功',
    description: '攻击是否成功的布尔判断。',
    placeholder: 'engine.attack_success',
    defaultValue: 'engine.attack_success',
    type: 'boolean',
    searchable: true,
    aggregatable: true,
    defaultSelected: false,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'same',
    sortFieldMode: 'same',
    queryFieldMode: 'same',
  },
  {
    key: 'attackSuccessConfidence',
    label: '成功置信度',
    description: '攻击成功判断的置信度。',
    placeholder: 'engine.attack_success_confidence',
    defaultValue: 'engine.attack_success_confidence',
    type: 'keyword',
    searchable: true,
    aggregatable: true,
    defaultSelected: false,
    detailOnly: false,
    statsKind: 'terms',
    aggregationFieldMode: 'same',
    sortFieldMode: 'same',
    queryFieldMode: 'same',
  },
  {
    key: 'attackSuccessReason',
    label: '成功原因',
    description: '攻击成功判断的解释说明。',
    placeholder: 'engine.attack_success_reason',
    defaultValue: 'engine.attack_success_reason',
    type: 'keyword',
    searchable: false,
    aggregatable: false,
    defaultSelected: false,
    detailOnly: true,
    statsKind: 'none',
    aggregationFieldMode: 'same',
    sortFieldMode: 'same',
    queryFieldMode: 'same',
  },
  {
    key: 'payloadPrintable',
    label: '可打印 Payload',
    description: '可打印化后的 Payload 内容。',
    placeholder: 'payload_printable',
    defaultValue: 'payload_printable',
    type: 'text',
    searchable: false,
    aggregatable: false,
    defaultSelected: false,
    detailOnly: true,
    statsKind: 'none',
    aggregationFieldMode: 'same',
    sortFieldMode: 'same',
    queryFieldMode: 'same',
  },
  {
    key: 'payload',
    label: '原始 Payload',
    description: '原始 Payload 字段。',
    placeholder: 'payload',
    defaultValue: 'payload',
    type: 'binary',
    searchable: false,
    aggregatable: false,
    defaultSelected: false,
    detailOnly: true,
    statsKind: 'none',
    aggregationFieldMode: 'same',
    sortFieldMode: 'same',
    queryFieldMode: 'same',
  },
  {
    key: 'packet',
    label: '原始 Packet',
    description: '原始 Packet 字段。',
    placeholder: 'packet',
    defaultValue: 'packet',
    type: 'binary',
    searchable: false,
    aggregatable: false,
    defaultSelected: false,
    detailOnly: true,
    statsKind: 'none',
    aggregationFieldMode: 'same',
    sortFieldMode: 'same',
    queryFieldMode: 'same',
  },
];

export const defaultAlertFieldMappings: AlertFieldMappings = alertFieldMappingSchema.reduce<AlertFieldMappings>((current, item) => {
  current[item.key] = item.defaultValue;
  return current;
}, {} as AlertFieldMappings);